### PR TITLE
Add chromium tests for hwacc encoding for vp8/vp9 codecs

### PR DESCRIPTION
**Pull request by petitfou**

### CODE REVIEW

**Review by mckees — CHANGES_REQUESTED** [review]
The VP8 test fails with this:
Error: GPU usage is higher after (hardware acceleration disabled) compared to before (hardware acceleration enabled).

**Comment by petitfou** [comment]
> The VP8 test fails with this: Error: GPU usage is higher after (hardware acceleration disabled) compared to before (hardware acceleration enabled).

Depending on the platform, the support of VP8/VP9 can be missing, hence the test fails, i do not know how we could handle this

**Comment by mckees** [comment]
As we discussed earlier, it feels like we should filter the tests by whether or not they support the current platform. It sounds like that's feasible, so I don't think we should expect anyone running media tests to know which tests *should* fail.

**Comment by petitfou** [comment]
> 



> As we discussed earlier, it feels like we should filter the tests by whether or not they support the current platform. It sounds like that's feasible, so I don't think we should expect anyone running media tests to know which tests _should_ fail.

Done

**Review by mckees — APPROVED** [review]

**Pull request merged**
